[profile.default]
solc_version = '0.8.23'
src = "contracts"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 8

[fuzz]
runs = 1000

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[profile.rpc_storage_caching]
chains = "all"  # or specific chain IDs
endpoints = "all"  # or specific URLs

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = "base" }
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = "84532", url = "https://api-sepolia.basescan.org/api" }
